module.exports = {
  main: 'src/public/entries/main',
  company: 'src/public/entries/company',
  developers: 'src/public/entries/developers',
  product: 'src/public/entries/product',
  wallet: 'src/public/entries/products/wallet',
  token: 'src/public/entries/products/token',
  dex: 'src/public/entries/products/dex',
  smartContracts: 'src/public/entries/smartContracts',
  getWaves: 'src/public/entries/getWaves',
  error404: 'src/public/entries/error404',
  wavesNG: 'src/public/entries/wavesNG',
  mining: 'src/public/entries/mining',
  leasing: 'src/public/entries/leasing',
  cookieConsent: 'src/public/cookieConsent',
};
